name: Metrics

on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  metrics-left:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: left
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.left.svg

          # Options
          user: wuzihao051119
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 6
          plugin_languages_ignored: html, css, 4D, q
          plugin_languages_details: bytes-size, percentage
          plugin_languages_aliases: Jupyter Notebook:ipynb
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 6
          plugin_starlists_languages_ignored: html
          plugin_starlists_languages_aliases: Jupyter Notebook:ipynb
          plugin_starlists_limit_repositories: 0
          plugin_starlists_only: Learning
          config_order: followup, languages, starlists

  metrics-right:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: right
        uses: stalomeow/metrics@projects-v2
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.right.svg

          # Options
          user: wuzihao051119
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B
          plugin_achievements_ignored: member, worker, explorer, automator, infographile
          config_order: topics, achievements
